FROM node:18-alpine

# Required
ARG NUXT_PUBLIC_OPENAI_API_KEY
ENV NUXT_PUBLIC_OPENAI_API_KEY=${NUXT_PUBLIC_OPENAI_API_KEY}
ARG NUXT_PUBLIC_API_MODEL
ENV NUXT_PUBLIC_API_MODEL=${NUXT_PUBLIC_API_MODEL}

# Optional, for customizing endpoints
ARG NUXT_PUBLIC_AI_ENDPOINT
ENV NUXT_PUBLIC_AI_ENDPOINT=${NUXT_PUBLIC_AI_ENDPOINT}

# For Telemetry, optional
ARG NUXT_PUBLIC_SITE_NAME
ENV NUXT_PUBLIC_SITE_NAME=${NUXT_PUBLIC_SITE_NAME}
ARG NUXT_PUBLIC_SITE_URL
ENV NUXT_PUBLIC_SITE_URL=${NUXT_PUBLIC_SITE_URL}

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "preview" ]